### ISSUE TITLE
Subscriptions categories array

### ISSUE THREAD

**Issue by lvialle** [ceee/FeedlySharp#1]
Hello,

first thanks for writing this library, it's going to be very useful. I just started using it but I already found a problem when parsing the subscriptions. The JSON cannot deserialize because you are replacing the array chars by the json start char:

https://github.com/ceee/FeedlySharp/blob/master/FeedlySharp/FeedlyHttpClient.cs#L131

With this line you cannot parse the nested arrays. Any reason for doing that?

**Comment by ceee** [comment]
Hi! :-)

As stated in the readme, the lib is not ready yet (and not tested too).
I will start writing tests and see which methods fail in the upcoming weeks (including the subscriptions).

You can for sure submit a PR if you would like to ;)

Bye Tobi
